import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Swal from 'sweetalert2'
import { useRouter } from 'next/router'
import { onLogin } from '../services/auth'
import { useState } from 'react';

export default function Home() {
const router = useRouter()
  
const [vistPassword, setVisPassword] = useState(false)
  
const submitLogin = async (e) => {
  e.preventDefault()
  // console.log(e)
  let data = e.target
  // console.log(data)
onLogin(data).then((response) => {
  // console.log(response)
    // if (response.status == 1 ) {
       switch (response.data.status) {
        case 1:
          window.localStorage.setItem('token', response.token);
          window.localStorage.setItem('user_data', JSON.stringify(response.data));
          window.localStorage.setItem('expires_in', JSON.stringify(response.expires_in));
          router.replace("/dashboard/CheckinList");
          break;
        case false:
          Swal.fire({
              title: 'เข้าสู่ระบบ ไม่สำเร็จ!',
              text: 'Email or Password ไม่ถูกต้อง',
              icon: 'error',
              confirmButtonText: 'ตกลง',
              confirmButtonColor: '#FFA688',
            })

          break;
        default:
          Swal.fire({
            title: 'เกิดข้อผิดพลาดในการ เข้าสู่ระบบ!',
            text: "กรุณาลองใหม่อีกครั้ง",
            icon: 'error',
            showConfirmButton: false,
            confirmButtonText: 'ตกลง',
            confirmButtonColor: '#FFA688',
          })
          break;
      }
    });
  };

const visibledPassword = () => {
  if (vistPassword == true) {
    setVisPassword(false);
    document.getElementById('password').type = 'password';
  } else {
    setVisPassword(true);
    document.getElementById('password').type = 'text';
  }
};

return (
  <div className='Box-login-Admin-checkInMan : h-full top-6-5p bottom-15p left-30p right-30p'>
    <Head>
      <title> Log in | Chack-In-Man </title>
      <meta name = "description" content='Generated by create next app' />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>

        <div className='Box-Singin-Admin-CheckinMan : b-grey p-10p border-8px shadow'>
        <h1 className='Box-Herder-Title-Login-Admin-CheckinMan : fort-knit s-30px center'> Chack in Man <br/> Admin </h1><br/>

            <form id='form-login' onSubmit={submitLogin} method="post" className="relative">
              <label className='block'>
                <Image src='/assets/images/icons/icon-account.png' alt='Varcel Password' width={40} height={40}/>
                <span className='Title-Id-Login : fort-knit s-20px'> Email </span><br/>
                <input type = 'email' name='email' className='Box-username-login-list-check-in : gay-h s-black-h left-7p left-m-14px  w-full left-3p right-1p s-15px h-40px black  b-white white fort-knit box-shadow border-5px' required placeholder='Email'/>
              </label><br/>

              <label className='Title-password-Login : fort-knit s-20px'>
                <Image src='/assets/images/icons/icon-password-64.png' alt='Varcel Password' width={40} height={40}/>
                <span className='left'> Password </span><br/>
                {/* <Image src='/assets/images/icons/shield.gif' alt='Varcel Password' width={50} height={50} /> */}
                <span className='ck-image-password left-[92%]'/>
                <span className='ck-input-login-eye left-[92%]' onClick = {() => visibledPassword()}></span>
                <input type='password' name='password' id='password' className='Box-password-login-list-check-in : gay-h s-black-h left-7p left-m-14px  w-full left-3p right-1p s-15px h-40px black  b-white white fort-knit box-shadow border-5px ' required placeholder='Password'/>
              </label><br/><br/>
            <label className='"'>
              <input className='' type='checkbox' id='checkbox' name='checkbox'/> <label className=' fort-knit text-9xl white'> จำฉันไว้ในระบบ </label>
            </label><br/><br/>

            <label className=''>
              <button type='submit' className='Box-Sign-in-admin :  s-15px h-40px w-full white fort-knit b-black border-5px box-shadow' id='btn-login' name='btn_login' value='submit'> Sign in </button>
            </label><br/><br/>

            <Link href='/dashboard/CheckinList'>
              <label className=''>
                <p className='Title-ResetPassword-Login : white1-h fort-knit center'>ลืมรหัสผ่าน ?</p>
              </label>
            </Link>
            </form>
      </div>
    </main>

    <footer>

    </footer>
  </div>
)

}